spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /api/ping
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: JAVA_OPTIONS
              value: "-Dswarm.project.stage.file=file:///app/config/project-defaults.yml"
      volumes:
        - configMap:
            name: app-config
            items:
            - key: "app-config.yml"
              path: "project-defaults.yml"
          name: config
